name: App am Leben erhalten

on:
  schedule:
    # Wir pingen alle 4 Stunden
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Deep Wake (Vollständiger Seitenaufruf)
        run: |
          # Wir laden die Seite herunter und werfen das Ergebnis weg,
          # aber der Download zwingt Streamlit zum Starten.
          curl -L -s https://lennart-voss-homepage.streamlit.app/ > /dev/null
          
          # Sicherheitshalber ein zweiter Aufruf nach 10 Sekunden
          sleep 10
          curl -L -s https://lennartvoss.streamlit.app/ > /dev/null
