name: App am Leben erhalten

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Hard-Reset Weckruf
        run: |
          wget --spider --user-agent="Mozilla/5.0" --tries=3 --timeout=30 https://lennartvoss.streamlit.app/
